### ISSUE TITLE
Performance issues on CP index with large number of elements

### ISSUE THREAD

**Issue by mildlygeeky** [aelvan/Preparse-Field-Craft#10]
Hey!

Loving Preparse — it's been a total life-saver for some interesting cases where it makes a huge difference to figure out things at save-time rather than at run-time.

The only issue I have found thus far has been performance issues in the control panel — we have a site with several thousand entries, and many fields, and found that after installing Preparse the entry index tables slowed to a crawl (around 10 seconds to load despite running PHP 7 and 4 GB RAM).

As I dug in, I found that although we set our Preparse fields to not show up in the entry columns, it looks like quite a bit of code was still being run on each entry as part of the "_getEnabledPreparseColumns" function. If I comment out the "getEntryTableAttributeHtml" code, the entry table goes from around 30 seconds on my local back down to ~ 1 second.

Would it be possible to either make this code more performant, or have a master "kill switch" for disabling Preparse fields in element index tables? Thinking that a simple settings screen with a lightswitch to disable all Preparse fields from element tables could allow the plugin to very quickly know whether or not to run all that additional code.

**Comment by aelvan** [comment]
Merged your pull request, thanks for contributing!
