### ISSUE TITLE
Have the ability to set the database field type

### ISSUE THREAD

**Issue by zizther** [aelvan/Preparse-Field-Craft#12]
It would be good to have the ability to choose what database field type the Preparse field is.

I am using the Preparse field to calculate a value. I am then using these entry values for a search. When the database field type is `TEXT`, as it currently is, the search results are not accurate, when setting it to `INT` it returns accurate results.

**Comment by aelvan** [comment]
I see your point. I'll look into it.

**Comment by aelvan** [comment]
This was kindly added by @marionnewlevant in version 0.2.2.
