### ISSUE TITLE
Search index not updating with change preparse contents

### ISSUE THREAD

**Issue by bossanova808** [aelvan/Preparse-Field-Craft#17]
Hi Andre

I have a prepare field which jsut does a simple include of some html content from  files.

I am using a console command to trigger a re-save of these elements in the hope of getting changes to content in to the Craft search index.

However, this is not working as expected - removed words remain in the index, and new ones don't appear, despite `$success = craft()->entries->saveEntry($entry);` reporting success.

I was chatting with Benjamin Fleming (of Neo fame) - about this - he as some code that updates search index for neo here - https://github.com/benjamminf/craft-neo/blob/dev/neo/tasks/Neo_GetSearchKeywordsTask.php

....but to be honest I expected it to (tm) 'Just Work' by triggering the re-save.  Any ideas why this might not work??

**Comment by carlcs** [comment]
If you use the "Parse before save" option, the search index should update correctly. Otherwise Preparse has to utilize `BaseElementType::saveElement()` to re-save the entry after the original save and this function doesn't update the search indexes unfortunatelly.

**Comment by aelvan** [comment]
@bossanova808 Can you confirm if the new "Parse before save" option fixes this?

**Comment by bossanova808** [comment]
I can confirm @aelvan @carlcs that the new 'parse before save' solves the issue for me and my console command is now working just as intended - fabulous, and thanks!!  It's *way* quicker than manually updating search indexes etc...
