### ISSUE TITLE
Entry reorder won't update field in structure section

### ISSUE THREAD

**Issue by pauliusef** [aelvan/Preparse-Field-Craft#18]
Hi Andre,

In my preparse field I have a setup that uses information from the parent entry. However, when I change the place of the entry in the structure by drag&drop, the preparse field value doesn't get updated.

After some digging in Craft code I found out that it doesn't save the entry when I move the entry in the hierarchy. Only a couple of related fields are changed and saved. First the `StructuresController.actionMoveElement` is fired, which in turn calls various methods in the `StructuresService`. It then does the updating and fires a `onMoveElement` event after everything is finished. 

Maybe it is wise to attach plugin functionality to this event so that fields, which depend on parent field values, would be updated?

**Comment by aelvan** [comment]
I've added support for parsing on structures.onMoveElement to 0.3.4. It's behind a field config setting, since it results in elements being saved one extra time during move.
