### ISSUE TITLE
Remove initial whitespace from tag?

### ISSUE THREAD

**Issue by badlydrawnrob** [aelvan/Preparse-Field-Craft#2]
I've been using [this fix](http://craftcms.stackexchange.com/questions/11749/limit-search-results-for-users-by-tag-and-limit-to-5-tags/11783#11783) to pull out the first 5 tags from a custom tags field.

Without using `{% spaceless %}`, this is returned: `value=" tagOne tagTwo tagThree"` — the preparsed tag list always has an initial whitespace character. This is a problem as `tagOne` is rendered unsearchable (unless you include the whitespace).

This can be resolved by using the following snippet:

```
{% spaceless %}
    {% for tag in user.specialismTags.limit(5) %}
        {{ tag.title }}
    {% endfor %}
{% endspaceless %}
```
Which will output: `value="tagOne tagTwo tagThree"`. If you leave out any spaces in the template, the list is returned without spaces:

```
{% for tag in user.specialismTags.limit(5) %}{{ tag.title }}{% endfor %}
```

Outputs: `value="tagOnetagTwotagThree"`

I don't know if there's any way around this without using `{% spaceless %}, but thought I should flag it up. It seems odd the plugin would return a space *before* the first tag.

**Comment by aelvan** [comment]
Whitespace control can either be done in the preparsed twig snippet, or in the template that uses the preparse fields value. Removing whitespace automatically would make Preparse Field unusable in cases where you actually want and need the correct whitespace. Which is the reason why twig leaves it in there in the first place. 

I'm thinking that this could be a field setting, though. I'll add it to my todo-list.
