### ISSUE TITLE
FR: Add decimal places for Number field

### ISSUE THREAD

**Issue by johndwells** [aelvan/Preparse-Field-Craft#20]
We use Preparse to save a calculated sale price based on a original price field and a percentage sale.  If we select the Number field type, the decimal place truncates to zero. If we leave it as a text field, then we cannot do queries based on a sale price range.

So - it would be great to expose an option to specify decimal places, in the same way that Craft's own Number fieldtype does.

It might be worthwhile at the same time to establish the same length as Craft does - 12 digits as opposed to 10 (from what I can tell when looking at the `craft_content` table).

Thanks - this plugin is _invaluable_!!!

**Comment by aelvan** [comment]
This has been added to v0.3.3. Thanks for the suggestion, it makes the field more useful. :)
