### ISSUE TITLE
Preparse asset dynamic path in matrix block

### ISSUE THREAD

**Issue by pl-mnm** [aelvan/Preparse-Field-Craft#24]
Hi there,

I have a matrix block with two fields: an asset and preparse. The asset directory path is pointing to `{ preparseField }`.

I get a "cannot resolve subpath" error when I save the entry with the asset, but it works fine when I first save the entry without the asset and save it a second time with the asset.

I tried with "parse before save" enabled but no luck. Is this even possible?

Thanks in advance.

**Comment by aelvan** [comment]
No, as far as I can tell, it's not possible to get the preparse field to parse before the settings for the asset field is parsed. You'd need to find some other way of accomplishing what you're trying to do, sorry.
