### ISSUE TITLE
`elements.onSaveElement` performance concerns

### ISSUE THREAD

**Issue by timkelty** [aelvan/Preparse-Field-Craft#27]
It might be worth a note in the README that with the default field settings (saving content on `elements.onSaveElement`), your entry is always going to be saved twice.

If you're doing other heavy lifting on save, this can cause problems.

It seems like you could get around this perhaps by calling `Craft\ContentService::saveContent` instead, in your `elements.onSaveElement` handler.

Seems wasteful to save the entire entry again.

**Comment by aelvan** [comment]
I see what you're saying. But I actually think it's essential that `saveElement` is called after the preparse fields are parsed, or else other plugins that rely on `elements.onSaveElement` wouldn't get called with the final data. 

But it's definitely a possible performance caveat which maybe deserves a note in the docs. The way preparse field works isn't right for every project, and there're other approaches that could be taken if you need to save data `onSaveElement`, without storing the value on a field in the element and resaving.

**Comment by timkelty** [comment]
Yep, agreed on all accounts.
Just wanted to bring it up for anyone else having issues.
