### ISSUE TITLE
Matrix query working in templates but not in preparse field.  

### ISSUE THREAD

**Issue by shornuk** [aelvan/Preparse-Field-Craft#36]
Hi, 
Think I've found an issue. 

I have a simple template query for a matrix field. 
Queries like the following work in the templates
```
{{ entry.matrixField.matched('1').total() }}
{{ entry.matrixField.matched('not 1').total() }}
```

Obviously I'm trying to get the total matrix rows that match the criteria  (`matched` field is a lightswitch field)
Running this in a Preparse field doesn't work. Am I doing something wrong?

**Comment by wbrowar** [comment]
Hi @aelvan and @shornuk.. I'm running into a similar issue, but the query works and it's actually removing blocks from my matrix. I wonder if something's up with re-saving matrix and/or related fields in general.

Here's what my query looks like:
```twig
{{ entry.matrixField.type('fieldTypeHandle').count() }}
```

I have three block types (call them `a`, `b`, and `c`).. When saving an entry with the prepare field on, all blocks of block types `b` and `c`, but `a` works just fine (`a` happens to be the field I'm querying for, too). You can add/delete `a` blocks, but if you add a `b` or `c` block, they do not save with the entry. Removing the prepare field allows the matrix field to work just fine.

I'm on Craft `3.0.7` if that helps.

**Comment by carlcs** [comment]
@wbrowar is this a typo in your example, because in the Craft 3 version the entry being saved is available via a variable named `element`?

The issue you’re running into is that applying params to an element query object isn’t cloning the element any more in Craft 3. So you need to clone the object yourself, otherwise you’re overriding the Matrix blocks set to be saved.

```{{ clone (entry.matrixField).type('fieldTypeHandle').count() }}```

@shornuk you on Craft 3 as well?

**Comment by shornuk** [comment]
@carlcs yes, Craft 3

**Comment by carlcs** [comment]
Ok, so try to clone the query object. 
https://docs.craftcms.com/v3/changes-in-craft-3.html#element-queries
