### ISSUE TITLE
Float Issue and/or Feature Request

### ISSUE THREAD

**Issue by theskyfloor** [aelvan/Preparse-Field-Craft#39]
Hey,

So I am using a preparse field set to float to store numeric values with decimals. I am searching like this:

`floatField : ['and', '>= 11.4','<= 198.8']`

and entry with the value of `11.4` isn't returning for that query.

@carlcs was able to reproduce... oddly enough this behaviour only happens on a float field, when set to decimal or text the comparison is fine. It seems like this is an issue with the float column type for reasons explained in this article:

https://lists.mysql.com/mysql/201710

> The difference is that, for example, .01 can be represented exactly
> in decimal; but float types are binary, so .01 cannot be represented
> exactly. This can lead to all kinds of trouble when doing arithmetic,
> the errors accumulate.

It seems with all of this in mind it would make sense to convert float fields to decimal in preparse or to at least offer decimal as an option when setting the column type.

Thanks!

**Comment by aelvan** [comment]
Fixed in v1.0.1.
