### ISSUE TITLE
Suggested fix for Craft 2.5 compatibility with Customizable Element Indexes

### ISSUE THREAD

**Issue by webmarks** [aelvan/Preparse-Field-Craft#4]
In noticed that the Preparse field isn't showing on the list of available fields in the new Customizable Element Indexes table of Craft 2.5.

Looks like line 4 of PreparseField_PreparseFieldType.php needs to be changed from
`class PreparseField_PreparseFieldType extends BaseFieldType
`
to
`class PreparseField_PreparseFieldType extends BaseFieldType implements IPreviewableFieldType
`
and it works.

**Comment by carlcs** [comment]
If this gets implemented I suggest to make it optionally, configurable from field settings. There's reasons you don't want a field to be available.
