### ISSUE TITLE
Migration for Craft3

### ISSUE THREAD

**Issue by bossanova808** [aelvan/Preparse-Field-Craft#42]
Hi Andre

Any chance of knocking up a migration for those of us upgrading from C2?

I can hack/write a query to deal with changing the component class, but usually there is a bit more to it than that and it would be HUGELY useful if there was a proper migration in place for these.

As part of a huge upgrade, I have to dump by C3 database and re-upgrade my C2 one on fairly regular occasions, and each time these field types / settings don't carry over.

**Comment by bossanova808** [comment]
@thisisjamessmith 

The fields just need to be set to the new class:
```php
       
        // AELVAN PREPARSE FIELDS
        print("Preparse fields\n");
        $db = Craft::$app->getDb();
        $db->createCommand()->update('{{%fields}}', [
            'type' => PreparseField::class
        ], ['type' => 'PreparseField_Preparse'])->execute();

```
I run that ^ in a console controller command I have a bunch of custom update stuff in.

Then they should work as normal but I can't actually confirm I have tested that bit yet as such...

**Comment by bossanova808** [comment]
(I don't think settings have changed or anything but would be great to get some input from @aelvan)

(As a random side comment, I'm really surprised how few Craft plugins have nicely attended to V2 -> V3 upgrade issues like this, and the general feedback around slack/github that most folks aren't actually doing any/many C2 -> C3 site upgrades as such - because it's seen as to too hard.  A feeling I have some sympathy for as my very large upgrade has been a genuine PITA in all.)

**Comment by aelvan** [comment]
Was added by @carlcs in 1.0.5.
