### ISSUE TITLE
Throws exception on New Field creation in Craft 3.1.19

### ISSUE THREAD

**Issue by matthillco** [aelvan/Preparse-Field-Craft#49]
I just tried this plugin for the first time, and it throws an error as soon as I click New Field from the Field setup screen:

```
Unknown Property – yii\base\UnknownPropertyException
Getting unknown property: aelvan\preparsefield\fields\PreparseFieldType::model
```

I've tried disabling all other plugins which made no difference. Any ideas what might be causing this?

Craft 3.1.19, Preparse Field v1.0.5.1

Stack trace copied here: https://0bin.net/paste/BgCN5CB-Fw339Vmf#vRWiHnOvBik49OP4brIOGdynygUoThVPF-NHFcIHZwb

**Comment by mmikkel** [comment]
Hi @matthillco – I'm not immediately able to reproduce this on Craft 3.1.19. Which PHP and MySQL/Postgres versions are you running?

Please see this issue for a similar sounding issue (TLDR; try deleting your `/storage/compiled_classes/` folder and/or clearing opcache if it's enabled).

**Comment by matthillco** [comment]
Thanks for the swift reply @mmikkel. I deleted the compiled classes (and indeed, everything inside 'storage/runtime') but no change. I'm running on WampServer 3.1.3 on Windows with the following: 
Apache 2.4.9, MySQL 5.6.17 and PHP 7.0.3. I'm not sure how to clear opcache in this environment.

**Comment by carlcs** [comment]
@matthillco are you adding the field to a Matrix block type, or does this happen as soon as you click the New Field button at Settings > Fields?

**Comment by matthillco** [comment]
Hi @carlcs, it happens right after clicking the **New Field** button in **Settings > Fields**.

**Comment by mmikkel** [comment]
Hi @matthillco – just cut a new release [1.0.6](https://github.com/aelvan/Preparse-Field-Craft/releases/tag/v1.0.6); can you give it a go and see if it fixes your issue? Thanks!

**Comment by matthillco** [comment]
Awesome, that fixes it. Thank you :)
