### ISSUE TITLE
Preparse field holding on to old data

### ISSUE THREAD

**Issue by tinchalamo** [aelvan/Preparse-Field-Craft#51]
I have a `partner` entries field type that I'm saving to a preparse field like so: `{{ element.partner.one().title }}`. When I add an entry to the partner field and save the preparse field populates accordingly, but if I remove the related entry from the partner field and save the entry again the field is still populated with the previously related entry.

If I add a totally different entry to the partner field and save then the preparse field will update accordingly and be populated with the new related entry, but once again I cannot update the contents of the preparse field by removing the related entry as the preparse field still holds on to the data event after save.

**Comment by mmikkel** [comment]
What's probably happening here, is that Twig is throwing a runtime error under the hood, preventing the Preparse field's value from rendering, when you try to render `partner.one().title`, and the `partner` field is empty.

Try appending the `|default` filter to prevent the runtime error from happening:

```twig
{{ element.partner.one().title|default }}
```

**Comment by tinchalamo** [comment]
I ended up converting it to a Matrix field since I needed some additional options and it seems to be updating appropriately now. Thanks for getting back!
