### ISSUE TITLE
Using preparse fields with SEOmatic's sitemaps causes duplicate sitemap generation tasks

### ISSUE THREAD

**Issue by jsunsawyer** [aelvan/Preparse-Field-Craft#61]
Here's a screenshot of the tasks being generated.
![Screen Shot 2020-02-10 at 4 56 32 PM](https://user-images.githubusercontent.com/1007191/74266292-ea7d6000-4cb8-11ea-8bd2-41cfbfc85a9b.png)

Without a preparse field, only one task is added and completes without issue.

With a preparse field, the second task always fails to run, pausing any other tasks.

Disabling preparse fields completely resolved this issue. We're not doing anything fancy. Even just adding a string causes this issue.

I was able to resolve it by enabling the `Parse before save` setting for each of our fields.

I'm not sure if this is an issue with preparse field or SEOmatic, but I figure this would be the first place to check as I haven't had issues with other plugins in SEOmatic.

Preparse Field v1.1.0
SEOmatic 3.2.42
Craft CMS 3.4.5

**Comment by jsunsawyer** [comment]
Upon further investigation, it looks like the stalled tasks is independent of the preparse field.

The preparse field's usage is only causing the 2nd `Generating films sitemap` task to trigger when saving a film.

Resaving a film with `Parse before save` creates a single task, and resaving again while that task is running causes subsequent ones to stall.

**Comment by aelvan** [comment]
Hi, 

The preparse field re-saves the element unless you have `Parse before save` toggled on, so it's to be expected that any tasks that are added on element save, is added twice. But why the task would stall is something to investigate further. Have you checked your logs, specifically `queue.log`, for any clues?

**Comment by jsunsawyer** [comment]
@aelvan Ah, that makes sense. So the resaving would indeed be causing SEOmatic to trigger its tasks again, redundantly.

I'm seeing no errors in my logs. Just subsequent tasks getting the `Reserved` status and never firing. I'll submit an issue to SEOmatic. Thanks!

**Comment by khalwat** [comment]
This ended up being a local dev setup issue
